### ISSUE TITLE
在 Callback 中调用的函数无法直接通过 `msg.sender` 判断 position 的 owner。

### ISSUE THREAD

**Issue by q3yi** [jeffishjeff/ampli-v1-core#2]
在下面需要使用 callback 调用的几个函数中：

1. [`Ampli.withdrawFungible`](https://github.com/jeffishjeff/ampli-v1-core/blob/5c7d684a5db13a40cc5c62669b2312054e21b68c/src/Ampli.sol#L143)
2. [`Ampli.withdrawNonFungible`](https://github.com/jeffishjeff/ampli-v1-core/blob/5c7d684a5db13a40cc5c62669b2312054e21b68c/src/Ampli.sol#L170)
3. [`Ampli.borrow`](https://github.com/jeffishjeff/ampli-v1-core/blob/5c7d684a5db13a40cc5c62669b2312054e21b68c/src/Ampli.sol#L184)

因为需要先调用 `Ampli.unlock`，再在 unlock 的回调函数中调用上述几个函数，所以其 `msg.sender` 一定是个 contract, 而且不会是一个固定的 contract, 会有不同的 operator 去调用 withdraw 去不同的地方做操作，所以这里不能通过 `msg.sender` 来判断 owner。

**Comment by jeffishjeff** [comment]
As discussed, core is intended to be invoked by a periphery router/operator, which will be the actual owners of positions. So this as designed unless we come up with something else clever
